### ISSUE TITLE
Improve behaviour of font size between desktop and mobile.

### ISSUE THREAD

**Issue by Lateworm** [qingxin-yuan/instanews#2]
I see that the font size is set to 24 px, while the project specifications call for 16px. I'm guessing this is because 16px looks very small on mobile, while 24px looks good on mobile. The problem is that 24px is too large on desktop. To fix this and make the font size look good on all devices, add this inside your head:
```<meta name="viewport" content="width=device-width, initial-scale=1">```

**Comment by rcass** [comment]
@qingxin-yuan Looking at your current index.html seems you have added this meta tag 👍 

The font sizes still need some work. In your Sass there are some calculations that need to be adjusted such as `2 * $base-font `
