### ISSUE TITLE
Improve positioning of items on the splash.

### ISSUE THREAD

**Issue by Lateworm** [qingxin-yuan/instanews#4]
When the page is initially loaded, I'm seeing a lot of empty black space with the selection box right at the very bottom and the logo extending off-screen. To solve this, I would recommend moving away from the use of % units on margin. They can also be troublesome in padding.

Have a look at lines 8 and 13 of _header.scss.
A margin is set to a 30% will actually be 30% of the width at its element's parent. In this case, that element is the body (essentially, the browser window). While this works great on mobile where our browser windows tend to be portraits, it's not working in a wide landscape desktop window.

<img width="1440" alt="screen shot 2017-10-24 at 8 31 00 pm" src="https://user-images.githubusercontent.com/28849529/31979215-4e4884ca-b8fa-11e7-8540-9da375dd9f10.png">

**Comment by rcass** [comment]
Another possible solution you might want to look into, is just removing that margin entirely and using Flexbox to get the desired vertical centering. 

Have a container around the items you want vertically centered, then set the flex-direction to column. 

`.container {
  display: flex;
  flex-direction: column;
} `

With the flex direction set to column, you can then set a property on the children/flex items to align-items: center, and that should result in those items becoming vertically centered. 

`.flex-children {
  align-items: center;
} `

Along with the issue outlined above, I noticed you have put a fixed height of 420px on the header. If you are trying the flex box method, there should be no reason for the static height number (instead you can put something more dynamic such as height: 100%).
